author = Artur Tarassow
email = atecon@posteo.de
version = 0.2
date = 2024-02-11
description = Collection of tools for doing PCA
tags = C10
min-version = 2023c
public = pcaEst pcaPrint pcaScreeplot pcaBiplot
help = pcaTools_help.md
sample-script = pcaTools_sample.inp
depends = logging PairPlot fsboost
